In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import ast

In [2]:
data = pd.read_csv('TRADES.csv')
data.sample(10)

                Port_IDs                                      Trade_History
87   4022565861939831809  [{'time': 1718985208000, 'symbol': 'BTCUSDT', ...
5    3987739404272887297  [{'time': 1718979652000, 'symbol': 'ONDOUSDT',...
108  3962024093501274881  [{'time': 1718987515000, 'symbol': 'ETHUSDT', ...
101  4013955990069013504  [{'time': 1718973014000, 'symbol': 'AAVEUSDT',...
132  3937714876784951296  [{'time': 1718956857000, 'symbol': 'BNBUSDT', ...
81   3944658614777849089  [{'time': 1718684963000, 'symbol': 'SOLUSDT', ...
36   4019895412775450368  [{'time': 1718986192000, 'symbol': 'ENSUSDT', ...
100  3977078013600312321  [{'time': 1718984203000, 'symbol': 'FILUSDT', ...
103  3858510226868015873  [{'time': 1718971397000, 'symbol': 'ETHUSDT', ...
34   4031414524297538817  [{'time': 1718986213000, 'symbol': 'ENSUSDT', ...

In [3]:
def parse_string_to_list_dict(string_data: str):
    try:
        return ast.literal_eval(string_data)
    except (SyntaxError, ValueError) as e:
        print(f"Error parsing string: {e}")
        return None

In [4]:
# parse_string_to_list_dict(data['Trade_History'][0])
# data.loc[113]  # Access row with index label 2
num_nan_rows = data.isna().any(axis=1).sum()
print(num_nan_rows)

1

In [5]:
def get_new_df(df: pd.DataFrame) -> pd.DataFrame:
#to get the desired dataframe for easy implementation later
    new_df = []
    column_names = []
    count=0
    for row in df.itertuples(index=False):

        try:
            current_port = row.Port_IDs
            trade_history = row.Trade_History
            trade_history = parse_string_to_list_dict(trade_history)
    
            for trade in trade_history:
                current_row = []
                current_row.append(current_port)
    
                for key, value in trade.items():
                    current_row.append(value)
    
                column_names = ["Port_IDs"].extend(list(trade.keys()))
                new_df.append(current_row)
        except:
            count+=1
            pass

    print(count)#count helping us to get whether we skipped the nan 
    return pd.DataFrame(new_df, columns=column_names)

In [6]:
new_data = get_new_df(data)

Error parsing string: malformed node or string: nan
1

In [7]:
new_data.shape

(211277, 15)

In [8]:
column_list = [
    'Port_IDs', 'time', 'symbol', 'side', 'price', 'fee', 'feeAsset', 'quantity', 
    'quantityAsset', 'realizedProfit', 'realizedProfitAsset', 'baseAsset', 
    'qty', 'positionSide', 'activeBuy'
]
new_data.columns = column_list

In [9]:
new_data.sample(10)

,Port_IDs,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy
28838,3956076827719377409,1718536241000,1000PEPEUSDT,SELL,0.012024,-0.042786,USDT,85.572673,USDT,1.152551,USDT,1000PEPE,7117.00,LONG,False
15523,3878631538480067329,1715700965000,BNBUSDT,BUY,567.000000,-0.038556,USDT,192.780000,USDT,6.120000,USDT,BNB,0.34,SHORT,False
22899,4011626972687000576,1718884266000,THETAUSDT,SELL,1.582500,-0.008308,USDT,16.616250,USDT,0.000000,USDT,THETA,10.50,BOTH,False
111797,4022641794255717633,1718700191000,1000PEPEUSDT,SELL,0.010843,-0.004001,USDT,20.005150,USDT,0.000000,USDT,1000PEPE,1845.00,SHORT,True
8660,3987739404272887297,1717653441000,BNBUSDT,SELL,697.750000,-0.003489,USDT,6.977500,USDT,0.000000,USDT,BNB,0.01,SHORT,False
5360,3987739404272887297,1718710429000,ENSUSDT,BUY,22.210000,-0.004442,USDT,8.884000,USDT,0.000000,USDT,ENS,0.40,LONG,True
200669,4017263283405469185,1717680891000,1000PEPEUSDT,BUY,0.014694,-0.200725,USDT,401.449310,USDT,1.783414,USDT,1000PEPE,27321.00,SHORT,True
41887,4035430878731345664,1718678609000,DOGEUSDT,BUY,0.120650,-0.344757,USDT,689.514750,USDT,0.000000,USDT,DOGE,5715.00,LONG,True
56284,3988071780777702657,1716620525000,BIGTIMEUSDT,SELL,0.212000,-0.036930,USDT,184.652000,USDT,0.688571,USDT,BIGTIME,871.00,BOTH,True
46579,3995532094997544704,1718580587000,ADAUSDT,BUY,0.416000,-0.019968,USDT,99.840000,USDT,0.000000,USDT,ADA,240.00,BOTH,False

In [10]:
new_data.shape#size of dataframe

(211277, 15)

In [11]:
print(new_data.dtypes)

Port_IDs                 int64
time                     int64
symbol                  object
side                    object
price                  float64
fee                    float64
feeAsset                object
quantity               float64
quantityAsset           object
realizedProfit         float64
realizedProfitAsset     object
baseAsset               object
qty                    float64
positionSide            object
activeBuy                 bool
dtype: object

In [12]:
for column in column_list:
    print(f"for column {column}: count of unique value:{new_data[column].nunique()}")
    #for calculating to see unnecessary features

for column Port_IDs: count of unique value:149
for column time: count of unique value:57220
for column symbol: count of unique value:154
for column side: count of unique value:2
for column price: count of unique value:78776
for column fee: count of unique value:184699
for column feeAsset: count of unique value:1
for column quantity: count of unique value:187836
for column quantityAsset: count of unique value:1
for column realizedProfit: count of unique value:94849
for column realizedProfitAsset: count of unique value:1
for column baseAsset: count of unique value:154
for column qty: count of unique value:32312
for column positionSide: count of unique value:3
for column activeBuy: count of unique value:2

In [13]:
port_column = data['Port_IDs']

In [14]:
def ROI(new_data: pd.DataFrame) -> pd.DataFrame:
    roi_results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Total Investment (BUY trades)
        total_investment = group[group["side"] == "BUY"]["quantity"].sum()
        
        # Total Returns (SELL trades)
        total_returns = group[group["side"] == "SELL"]["quantity"].sum()
        
        # Total Fees (in USDT)
        total_fees = group["fee"].sum()
        
        # ROI Calculation
        if total_investment > 0:
            roi = ((total_returns - total_investment + total_fees) / (total_investment - total_fees)) * 100
        else:
            roi = 0
        
        roi_results.append({"Port_IDs": port_id, "ROI": roi})
    
    roi_df = pd.DataFrame(roi_results)
    
    return roi_df

In [15]:
def PnL(new_data: pd.DataFrame) -> pd.DataFrame:
    pl_results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Total Investment (BUY trades)
        total_investment = group[group["side"] == "BUY"]["quantity"].sum()
        
        # Total Returns (SELL trades)
        total_returns = group[group["side"] == "SELL"]["quantity"].sum()
        
        # Total Fees (in USDT)
        total_fees = group["fee"].sum()
        
        # Realized Profit
        realized_profit = group["realizedProfit"].sum()
        
        # Profit or Loss Calculation
        profit_or_loss = total_returns - total_investment + total_fees + realized_profit
        
        pl_results.append({"Port_IDs": port_id, "Profit/Loss": profit_or_loss})
    
    pl_df = pd.DataFrame(pl_results)
    
    return pl_df

In [16]:
def sharpe_ratio(new_data: pd.DataFrame, risk_free_rate: float = 0.0, trading_days: int = 90) -> pd.DataFrame:

    sharpe_results = []
    
    # Created a copy and convert 'time' to datetime
    df = new_data.copy()
    df['datetime'] = pd.to_datetime(df['time'], unit='ms', errors='coerce')
    df['date'] = df['datetime'].dt.date
    
    # Processed each portfolio
    for port_id, group in df.groupby("Port_IDs"):
        # Prefered closed trades
        closed_trades = group[group["activeBuy"] == False]
        trades_to_use = closed_trades if not closed_trades.empty else group
        
        # Daily profit calculation
        daily_profit = trades_to_use.groupby("date")["realizedProfit"].sum().reset_index()
        
        # Fixed: Daily investment calculation
        buy_trades = trades_to_use[trades_to_use["side"] == "BUY"]
        # Changed the groupby operation to directly create a DataFrame with named columns
        daily_investment = (
            buy_trades.groupby("date")["quantity"]
            .sum()
            .to_frame(name="daily_investment")
            .reset_index()
        )
        
        # Merge daily profit and investment
        daily = pd.merge(daily_profit, daily_investment, on="date", how="left")
        daily["daily_investment"] = daily["daily_investment"].fillna(0)
        
        # Calculated daily returns
        daily["daily_return"] = np.where(
            daily["daily_investment"] > 0,
            daily["realizedProfit"] / daily["daily_investment"],
            0
        )
        
        # Calculated Sharpe ratio
        valid_returns = daily[daily["daily_investment"] > 0]["daily_return"]
        if len(valid_returns) < 2:
            sharpe = 0
        else:
            mean_return = valid_returns.mean()
            std_return = valid_returns.std()
            sharpe = ((mean_return - risk_free_rate) / std_return) * np.sqrt(trading_days) if std_return != 0 else 0
        
        sharpe_results.append({"Port_IDs": port_id, "Sharpe Ratio": sharpe})
    
    return pd.DataFrame(sharpe_results)

In [17]:
def MDD(new_data: pd.DataFrame) -> pd.DataFrame:
    mdd_results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Used only closed trades (activeBuy == False)
        closed_trades = group[group["activeBuy"] == False].copy()
        if closed_trades.empty:
            # If no closed trades, assumed no drawdown.
            mdd_results.append({"Port_IDs": port_id, "MDD": 0})
            continue
        
        # Sorted the trades in chronological order.
        closed_trades = closed_trades.sort_values(by="time")
        
        # Computed net profit for each trade: realizedProfit + fee
        # (Note: fee is negative so adding it subtracts the fee)
        closed_trades["net_profit"] = closed_trades["realizedProfit"] + closed_trades["fee"]
        
        # Computed cumulative net profit over time.
        closed_trades["cumulative_net"] = closed_trades["net_profit"].cumsum()
        
        # Compute the cumulative maximum of the cumulative net profit.
        closed_trades["cumulative_max"] = closed_trades["cumulative_net"].cummax()
        
        # Calculated drawdown at each trade.
        # If cumulative_max > 0, drawdown is (current - peak) / peak.
        # Otherwise, if no profit has been made (peak==0), we define drawdown as 0.
        closed_trades["drawdown"] = closed_trades.apply(
            lambda row: (row["cumulative_net"] - row["cumulative_max"]) / row["cumulative_max"]
            if row["cumulative_max"] > 0 else 0, axis=1)
        
        # Maximum drawdown is the minimum (most negative) drawdown observed.
        mdd = closed_trades["drawdown"].min()
        mdd_results.append({"Port_IDs": port_id, "MDD": mdd})
    
    # Created a DataFrame
    mdd_df = pd.DataFrame(mdd_results)
    return mdd_df

In [18]:
def Win_Rate(new_data: pd.DataFrame) -> pd.DataFrame:
    results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Prefered closed trades (activeBuy == False); if none, use all trades.
        closed_trades = group[group["activeBuy"] == False]
        trades_to_use = closed_trades if not closed_trades.empty else group
        
        total_trades = len(trades_to_use)
        # Counted winning trades: where realizedProfit > 0
        win_count = len(trades_to_use[trades_to_use["realizedProfit"] > 0])
        
        # Calculated win rate as percentage.
        rate = (win_count / total_trades) * 100 if total_trades > 0 else 0
        
        results.append({"Port_IDs": port_id, "Win Rate": rate})
    
    win_rate_df = pd.DataFrame(results)
    return win_rate_df

In [19]:
def Win_Positions(new_data: pd.DataFrame) -> pd.DataFrame:
    results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Used only closed trades (activeBuy == False)
        closed_trades = group[group["activeBuy"] == False]
        
        if not closed_trades.empty:
            # Counted profitable positions (realizedProfit > 0)
            wins_count = closed_trades[closed_trades["realizedProfit"].astype(float) > 0].shape[0]
            
            results.append({
                "Port_IDs": port_id,
                "Win_Positions": wins_count
            })
    
    # Created DataFrame
    win_positions_df = pd.DataFrame(results)
    return win_positions_df

In [20]:
def Total_Positions(new_data: pd.DataFrame) -> pd.DataFrame:
    results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Prefered closed trades (activeBuy == False) if available; otherwise, use all trades.
        closed_trades = group[group["activeBuy"] == False]
        trades_to_use = closed_trades if not closed_trades.empty else group
        
        total_trades = trades_to_use.shape[0]
        results.append({"Port_IDs": port_id, "Total Positions": total_trades})
    
    total_positions_df = pd.DataFrame(results)
    return total_positions_df

In [21]:
def check(metric: str, new_data: pd.DataFrame) -> pd.DataFrame:
    # Called the appropriate metric function based on the input string.
    if metric == 'ROI':
        new_frame = ROI(new_data)
    elif metric == 'PnL':
        new_frame = PnL(new_data)
    elif metric == 'Sharpe Ratio':
        new_frame = sharpe_ratio(new_data)  
    elif metric == 'MDD':
        new_frame = MDD(new_data)
    elif metric == 'Win Rate':
        new_frame = Win_Rate(new_data)
    elif metric == 'Win Positions':
        new_frame = Win_Positions(new_data)
    elif metric == 'Total Positions':
        new_frame = Total_Positions(new_data)
    else:
        new_frame = pd.DataFrame()
    if not new_frame.empty and len(new_frame.columns) >= 2:
        metric_value_col = new_frame.columns[1]
        
    return new_frame

In [22]:
metrics = ['ROI', 'PnL', 'Sharpe Ratio', 'MDD', 'Win Rate', 'Win Positions', 'Total Positions']
account_metric = None
for m in metrics:
    df_metric = check(m, new_data)
    
    # Rename the 'metrics' column to the metric name (e.g., 'ROI', 'PnL', etc.)
    df_metric = df_metric.rename(columns={"metrics": m})
    
    if account_metric is None:
        account_metric = df_metric
    else:
        account_metric = pd.merge(account_metric, df_metric, on="Port_IDs", how="outer")

In [23]:
account_metric['Win_Positions'] = account_metric['Win_Positions'].fillna(0)

In [28]:
account_metric.head(10)

,Port_IDs,ROI,Profit/Loss,Sharpe Ratio,MDD,Win Rate,Win_Positions,Total Positions
0,3672754654734989568,-7.399322,-4004.085376,3.952573,-31.691847,37.826087,87.0,230
1,3733192481840423936,0.423627,5386.251884,6.046070,-1.411886,83.283133,553.0,664
2,3768170840939476993,161.687802,1484.933223,0.000000,0.000000,0.000000,0.0,7
3,3784403294629753856,-3.703794,-11487.316628,1.579234,-0.355020,18.789906,618.0,3289
4,3786761687746711808,-11.412003,-3532.809350,5.282657,-1.003587,39.024390,16.0,41
5,3788465932399412480,-2.467197,-6886.068100,3.278663,-0.145310,65.280000,816.0,1250
6,3818233536529843712,-15.982368,-64262.955453,0.000000,-1.363986,66.225166,400.0,604
7,3819545518395756033,-6.534685,-3820.884427,7.910092,-0.031242,4.545455,2.0,44
8,3826087012661391104,-55.777830,-1159.276124,7.854031,-0.218252,78.461538,51.0,65
9,3858510226868015873,0.695569,2448.728827,-0.949681,-308.677724,27.232143,122.0,448

In [29]:
account_metric.isnull().sum()

Port_IDs           0
ROI                0
Profit/Loss        0
Sharpe Ratio       0
MDD                0
Win Rate           0
Win_Positions      0
Total Positions    0
dtype: int64

In [24]:
account_metric.to_csv('account_metrics.csv', index=False)

In [30]:
account_metric.shape

(149, 8)

In [31]:
account_metric.sample(10)

,Port_IDs,ROI,Profit/Loss,Sharpe Ratio,MDD,Win Rate,Win_Positions,Total Positions
18,3910887259807777281,-16.425783,-16290.221876,0.000000,-0.288709,28.571429,2.0,7
24,3925368433214965504,-4.076444,-30866.133017,8.502213,-0.067007,37.254902,228.0,612
117,4030626027667524352,0.273227,7086.644629,-1.283936,-64.956903,38.405797,53.0,138
73,3998572645139652353,0.881187,18607.142231,3.025978,-1.129437,27.338129,38.0,139
71,3995532094997544704,-1.109382,-49224.414686,-3.774762,0.000000,32.747396,1006.0,3072
127,4032403303704824321,0.463464,3866.019201,9.334591,-0.008307,57.142857,16.0,28
137,4037179073830813185,-9.162371,-13077.658544,0.000000,-0.003119,50.000000,25.0,50
100,4022641794255717633,-5.482405,-1144.375046,10.531978,-0.164776,84.180249,2634.0,3129
146,4040843843196854529,10.113067,12665.570580,0.000000,-0.046610,7.894737,3.0,38
141,4037785885739608577,40.447363,13835.526825,0.000000,-0.003422,34.337349,57.0,166

In [32]:
weights={'ROI':0.2,	'Profit/Loss':0.4,	'Sharpe Ratio':0.1,	'MDD':0.1,	'Win Rate':0.15,	'Win_Positions':0.05, 'Total Positions':0.0}

In [33]:
def composite_ranking(metrics_df: pd.DataFrame, weights: dict) -> pd.DataFrame:
    df = metrics_df.copy()

    for metric, weight in weights.items():
        if metric not in df.columns:
            continue  # Skip if the metric is not present
        
        # Compute z-score normalization
        mean_val = df[metric].mean()
        std_val = df[metric].std()
        if std_val == 0:
            df[metric + '_norm'] = 0
        else:
            df[metric + '_norm'] = (df[metric] - mean_val) / std_val
        
        # For MDD, lower values are better, so invert the normalized value.
        if metric == 'MDD':
            df[metric + '_norm'] = -df[metric + '_norm']
    
    # Compute the composite score as a weighted sum of normalized scores.
    composite_scores = np.zeros(len(df))
    for metric, weight in weights.items():
        if metric not in df.columns:
            continue
        composite_scores += df[metric + '_norm'] * weight
    df['Composite Score'] = composite_scores
    
    # Sort portfolios by Composite Score in descending order
    df = df.sort_values(by='Composite Score', ascending=False).reset_index(drop=True)
    
    # Create a Rank column (1 = best)
    df['Rank'] = df.index + 1
    
    # Return only the columns of interest
    return df[['Port_IDs', 'Composite Score', 'Rank']]

In [34]:
ranked_data = composite_ranking(account_metric,weights);
ranked_data.head(20)

               Port_IDs  Composite Score  Rank
0   4020204877254599680         2.394740     1
1   3936410995029308417         2.185309     2
2   3944658614777849089         1.241694     3
3   4012994295026226176         0.993394     4
4   3768170840939476993         0.899488     5
5   3956048468100538880         0.663234     6
6   4030635536196756737         0.657893     7
7   3999240873283311617         0.574054     8
8   4004713168329653760         0.555595     9
9   4022641794255717633         0.520012    10
10  4029506971304830209         0.491584    11
11  4030392204221219329         0.484009    12
12  4037073643537925121         0.464368    13
13  3879821005658659073         0.389286    14
14  3926423286576838657         0.383935    15
15  4021669203289716224         0.370756    16
16  4031408429897920512         0.353442    17
17  3878631538480067329         0.346966    18
18  3733192481840423936         0.345270    19
19  3949329502284748801         0.344223    20