In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import ast

In [10]:
data = pd.read_csv('TRADES.csv')
data.sample(10)

                Port_IDs                                      Trade_History
121  4031673021422897664  [{'time': 1718980361000, 'symbol': 'BTCUSDT', ...
134  3910983669796782848  [{'time': 1718892527000, 'symbol': 'ONDOUSDT',...
89   4027747397961573889  [{'time': 1718985019000, 'symbol': 'ETHUSDT', ...
93   4035034554469394176  [{'time': 1718934367000, 'symbol': 'LDOUSDT', ...
22   3956076827719377409  [{'time': 1718980950000, 'symbol': '1000PEPEUS...
71   4037179073830813185  [{'time': 1718969833000, 'symbol': 'BNBUSDT', ...
88   3942630767220672256  [{'time': 1718986317000, 'symbol': '1INCHUSDT'...
130  4038768306117031680  [{'time': 1718979315000, 'symbol': 'DOGEUSDT',...
64   3960874214179953664  [{'time': 1718972086000, 'symbol': 'BTCUSDT', ...
98   3949329502284748801  [{'time': 1718911220000, 'symbol': 'ONDOUSDT',...

In [3]:
def parse_string_to_list_dict(string_data: str):
    try:
        return ast.literal_eval(string_data)
    except (SyntaxError, ValueError) as e:
        print(f"Error parsing string: {e}")
        return None

In [15]:
# parse_string_to_list_dict(data['Trade_History'][0])
# data.loc[113]  # Access row with index label 2
num_nan_rows = data.isna().any(axis=1).sum()
print(num_nan_rows)

1

In [16]:
def get_new_df(df: pd.DataFrame) -> pd.DataFrame:

    new_df = []
    column_names = []
    count=0
    for row in df.itertuples(index=False):

        try:
            current_port = row.Port_IDs
            trade_history = row.Trade_History
            trade_history = parse_string_to_list_dict(trade_history)
    
            for trade in trade_history:
                current_row = []
                current_row.append(current_port)
    
                for key, value in trade.items():
                    current_row.append(value)
    
                column_names = ["Port_IDs"].extend(list(trade.keys()))
                new_df.append(current_row)
        except:
            count+=1
            pass

    print(count)#count helping us to get whether we skipped the nan 
    return pd.DataFrame(new_df, columns=column_names)

In [17]:
new_data = get_new_df(data)

Error parsing string: malformed node or string: nan
1

In [18]:
new_data.shape

(211277, 15)

In [19]:
column_list = [
    'Port_IDs', 'time', 'symbol', 'side', 'price', 'fee', 'feeAsset', 'quantity', 
    'quantityAsset', 'realizedProfit', 'realizedProfitAsset', 'baseAsset', 
    'qty', 'positionSide', 'activeBuy'
]
new_data.columns = column_list

In [20]:
new_data.sample(10)

,Port_IDs,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy
5970,3987739404272887297,1718676246000,JASMYUSDT,SELL,0.033836,-0.075454,USDT,150.908560,USDT,0.000000,USDT,JASMY,4460.00,SHORT,False
176173,3949214983441029120,1717605978000,ORDIUSDT,SELL,57.419000,-0.014355,USDT,28.709500,USDT,0.000000,USDT,ORDI,0.50,SHORT,False
27376,4011626972687000576,1718328147000,SKLUSDT,SELL,0.065150,-0.030946,USDT,61.892500,USDT,-0.947539,USDT,SKL,950.00,BOTH,False
141703,3784403294629753856,1717578557000,ORDIUSDT,SELL,57.169000,-0.037160,USDT,74.319700,USDT,0.000000,USDT,ORDI,1.30,SHORT,False
139735,3946087913459823360,1718641222000,KSMUSDT,BUY,24.060000,-0.009624,USDT,19.248000,USDT,0.000000,USDT,KSM,0.80,BOTH,True
177258,3949214983441029120,1716457104000,BNBUSDT,BUY,613.870000,-0.015347,USDT,30.693500,USDT,0.006781,USDT,BNB,0.05,SHORT,True
151663,4013955990069013504,1718410629000,SKLUSDT,SELL,0.063880,-0.008202,USDT,41.010960,USDT,0.000000,USDT,SKL,642.00,SHORT,True
196166,4017263283405469185,1718752115000,1000PEPEUSDT,BUY,0.010950,-0.002508,USDT,5.015008,USDT,-0.066926,USDT,1000PEPE,458.00,SHORT,True
134085,3946087913459823360,1718983399000,1000SHIBUSDT,BUY,0.017822,-0.004999,USDT,9.998142,USDT,0.053669,USDT,1000SHIB,561.00,BOTH,True
203840,3988187872032603905,1718889905000,LDOUSDT,BUY,2.236900,-0.000049,USDT,64.870100,USDT,0.942222,USDT,LDO,29.00,SHORT,True

In [21]:
new_data.shape

(211277, 15)

In [22]:
print(new_data.dtypes)

Port_IDs                 int64
time                     int64
symbol                  object
side                    object
price                  float64
fee                    float64
feeAsset                object
quantity               float64
quantityAsset           object
realizedProfit         float64
realizedProfitAsset     object
baseAsset               object
qty                    float64
positionSide            object
activeBuy                 bool
dtype: object

In [23]:
for column in column_list:
    print(f"for column {column}: count of unique value:{new_data[column].nunique()}")

for column Port_IDs: count of unique value:149
for column time: count of unique value:57220
for column symbol: count of unique value:154
for column side: count of unique value:2
for column price: count of unique value:78776
for column fee: count of unique value:184699
for column feeAsset: count of unique value:1
for column quantity: count of unique value:187836
for column quantityAsset: count of unique value:1
for column realizedProfit: count of unique value:94849
for column realizedProfitAsset: count of unique value:1
for column baseAsset: count of unique value:154
for column qty: count of unique value:32312
for column positionSide: count of unique value:3
for column activeBuy: count of unique value:2

In [95]:
port_column = data['Port_IDs']

In [99]:
def ROI(new_data: pd.DataFrame) -> pd.DataFrame:
    roi_results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Total Investment (BUY trades)
        total_investment = group[group["side"] == "BUY"]["quantity"].sum()
        
        # Total Returns (SELL trades)
        total_returns = group[group["side"] == "SELL"]["quantity"].sum()
        
        # Total Fees (in USDT)
        total_fees = group["fee"].sum()
        
        # ROI Calculation
        if total_investment > 0:
            roi = ((total_returns - total_investment + total_fees) / (total_investment - total_fees)) * 100
        else:
            roi = 0
        
        roi_results.append({"Port_IDs": port_id, "ROI": roi})
    
    roi_df = pd.DataFrame(roi_results)
    
    return roi_df

In [100]:
def PnL(new_data: pd.DataFrame) -> pd.DataFrame:
    pl_results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Total Investment (BUY trades)
        total_investment = group[group["side"] == "BUY"]["quantity"].sum()
        
        # Total Returns (SELL trades)
        total_returns = group[group["side"] == "SELL"]["quantity"].sum()
        
        # Total Fees (in USDT)
        total_fees = group["fee"].sum()
        
        # Realized Profit
        realized_profit = group["realizedProfit"].sum()
        
        # Profit or Loss Calculation
        profit_or_loss = total_returns - total_investment + total_fees + realized_profit
        
        pl_results.append({"Port_IDs": port_id, "Profit/Loss": profit_or_loss})
    
    pl_df = pd.DataFrame(pl_results)
    
    return pl_df

In [101]:
def sharpe_ratio(new_data: pd.DataFrame, risk_free_rate: float = 0.0, trading_days: int = 90) -> pd.DataFrame:

    sharpe_results = []
    
    # Create a copy and convert 'time' to datetime
    df = new_data.copy()
    df['datetime'] = pd.to_datetime(df['time'], unit='ms', errors='coerce')
    df['date'] = df['datetime'].dt.date
    
    # Process each portfolio
    for port_id, group in df.groupby("Port_IDs"):
        # Prefer closed trades
        closed_trades = group[group["activeBuy"] == False]
        trades_to_use = closed_trades if not closed_trades.empty else group
        
        # Daily profit calculation
        daily_profit = trades_to_use.groupby("date")["realizedProfit"].sum().reset_index()
        
        # Fixed: Daily investment calculation
        buy_trades = trades_to_use[trades_to_use["side"] == "BUY"]
        # Changed the groupby operation to directly create a DataFrame with named columns
        daily_investment = (
            buy_trades.groupby("date")["quantity"]
            .sum()
            .to_frame(name="daily_investment")
            .reset_index()
        )
        
        # Merge daily profit and investment
        daily = pd.merge(daily_profit, daily_investment, on="date", how="left")
        daily["daily_investment"] = daily["daily_investment"].fillna(0)
        
        # Calculate daily returns
        daily["daily_return"] = np.where(
            daily["daily_investment"] > 0,
            daily["realizedProfit"] / daily["daily_investment"],
            0
        )
        
        # Calculate Sharpe ratio
        valid_returns = daily[daily["daily_investment"] > 0]["daily_return"]
        if len(valid_returns) < 2:
            sharpe = 0
        else:
            mean_return = valid_returns.mean()
            std_return = valid_returns.std()
            sharpe = ((mean_return - risk_free_rate) / std_return) * np.sqrt(trading_days) if std_return != 0 else 0
        
        sharpe_results.append({"Port_IDs": port_id, "Sharpe Ratio": sharpe})
    
    return pd.DataFrame(sharpe_results)

In [102]:
def MDD(new_data: pd.DataFrame) -> pd.DataFrame:
    mdd_results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Use only closed trades (activeBuy == False)
        closed_trades = group[group["activeBuy"] == False].copy()
        if closed_trades.empty:
            # If no closed trades, assume no drawdown.
            mdd_results.append({"Port_IDs": port_id, "MDD": 0})
            continue
        
        # Sort the trades in chronological order.
        closed_trades = closed_trades.sort_values(by="time")
        
        # Compute net profit for each trade: realizedProfit + fee
        # (Note: fee is negative so adding it subtracts the fee)
        closed_trades["net_profit"] = closed_trades["realizedProfit"] + closed_trades["fee"]
        
        # Compute cumulative net profit over time.
        closed_trades["cumulative_net"] = closed_trades["net_profit"].cumsum()
        
        # Compute the cumulative maximum of the cumulative net profit.
        closed_trades["cumulative_max"] = closed_trades["cumulative_net"].cummax()
        
        # Calculate drawdown at each trade.
        # If cumulative_max > 0, drawdown is (current - peak) / peak.
        # Otherwise, if no profit has been made (peak==0), we define drawdown as 0.
        closed_trades["drawdown"] = closed_trades.apply(
            lambda row: (row["cumulative_net"] - row["cumulative_max"]) / row["cumulative_max"]
            if row["cumulative_max"] > 0 else 0, axis=1)
        
        # Maximum drawdown is the minimum (most negative) drawdown observed.
        mdd = closed_trades["drawdown"].min()
        mdd_results.append({"Port_IDs": port_id, "MDD": mdd})
    
    # Create a DataFrame
    mdd_df = pd.DataFrame(mdd_results)
    return mdd_df

In [103]:
def Win_Rate(new_data: pd.DataFrame) -> pd.DataFrame:
    results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Prefer closed trades (activeBuy == False); if none, use all trades.
        closed_trades = group[group["activeBuy"] == False]
        trades_to_use = closed_trades if not closed_trades.empty else group
        
        total_trades = len(trades_to_use)
        # Count winning trades: where realizedProfit > 0
        win_count = len(trades_to_use[trades_to_use["realizedProfit"] > 0])
        
        # Calculate win rate as percentage.
        rate = (win_count / total_trades) * 100 if total_trades > 0 else 0
        
        results.append({"Port_IDs": port_id, "Win Rate": rate})
    
    win_rate_df = pd.DataFrame(results)
    return win_rate_df

In [104]:
def Win_Positions(new_data: pd.DataFrame) -> pd.DataFrame:
    results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Use only closed trades (activeBuy == False)
        closed_trades = group[group["activeBuy"] == False]
        
        if not closed_trades.empty:
            # Count profitable positions (realizedProfit > 0)
            wins_count = closed_trades[closed_trades["realizedProfit"].astype(float) > 0].shape[0]
            
            results.append({
                "Port_IDs": port_id,
                "Win_Positions": wins_count
            })
    
    # Create and sort DataFrame
    win_positions_df = pd.DataFrame(results)
    return win_positions_df

In [105]:
def Total_Positions(new_data: pd.DataFrame) -> pd.DataFrame:
    results = []
    
    for port_id, group in new_data.groupby("Port_IDs"):
        # Prefer closed trades (activeBuy == False) if available; otherwise, use all trades.
        closed_trades = group[group["activeBuy"] == False]
        trades_to_use = closed_trades if not closed_trades.empty else group
        
        total_trades = trades_to_use.shape[0]
        results.append({"Port_IDs": port_id, "Total Positions": total_trades})
    
    total_positions_df = pd.DataFrame(results)
    return total_positions_df

In [97]:
def check(metric: str, new_data: pd.DataFrame) -> pd.DataFrame:
    # Call the appropriate metric function based on the input string.
    if metric == 'ROI':
        new_frame = ROI(new_data)
    elif metric == 'PnL':
        new_frame = PnL(new_data)
    elif metric == 'Sharpe Ratio':
        new_frame = sharpe_ratio(new_data)  # note: adjust the function name if needed
    elif metric == 'MDD':
        new_frame = MDD(new_data)
    elif metric == 'Win Rate':
        new_frame = Win_Rate(new_data)
    elif metric == 'Win Positions':
        new_frame = Win_Positions(new_data)
    elif metric == 'Total Positions':
        new_frame = Total_Positions(new_data)
    else:
        new_frame = pd.DataFrame()
    if not new_frame.empty and len(new_frame.columns) >= 2:
        metric_value_col = new_frame.columns[1]
        
    return new_frame

In [112]:
import pandas as pd

# List of metrics to calculate
metrics = ['ROI', 'PnL', 'Sharpe Ratio', 'MDD', 'Win Rate', 'Win Positions', 'Total Positions']
account_metric = None
for m in metrics:
    df_metric = check(m, new_data)
    
    # Rename the 'metrics' column to the metric name (e.g., 'ROI', 'PnL', etc.)
    df_metric = df_metric.rename(columns={"metrics": m})
    
    if account_metric is None:
        account_metric = df_metric
    else:
        account_metric = pd.merge(account_metric, df_metric, on="Port_IDs", how="outer")

In [113]:
account_metric.shape

(149, 8)

In [114]:
account_metric.sample(10)

,Port_IDs,ROI,Profit/Loss,Sharpe Ratio,MDD,Win Rate,Win_Positions,Total Positions
39,3944658614777849089,142.507576,43513.847054,0.000000,-0.049407,40.000000,6.0,15
52,3966142151544441601,0.539985,9212.784023,3.170265,-1445.618621,52.413793,380.0,725
127,4032403303704824321,0.463464,3866.019201,9.334591,-0.008307,57.142857,16.0,28
100,4022641794255717633,-5.482405,-1144.375046,10.531978,-0.164776,84.180249,2634.0,3129
118,4030635536196756737,8.350227,40035.528452,12.136468,-0.029582,96.058091,463.0,482
92,4017110277719148289,0.847772,5498.769427,6.708204,-0.110677,56.862745,87.0,153
80,4004410127575640832,1.171730,5698.672414,10.207877,-0.208084,32.544379,110.0,338
85,4008804082027254529,-4.362974,-93794.400065,6.301431,-3.565747,36.280488,119.0,328
133,4035430878731345664,3.788370,4922.216071,0.000000,0.000000,47.368421,27.0,57
71,3995532094997544704,-1.109382,-49224.414686,-3.774762,0.000000,32.747396,1006.0,3072

In [119]:
weights={'ROI':0.2,	'Profit/Loss':0.4,	'Sharpe Ratio':0.1,	'MDD':0.1,	'Win Rate':0.1,	'Win_Positions':0.1, 'Total Positions':0.0}

In [116]:
def composite_ranking(metrics_df: pd.DataFrame, weights: dict) -> pd.DataFrame:
    df = metrics_df.copy()

    for metric, weight in weights.items():
        if metric not in df.columns:
            continue  # Skip if the metric is not present
        
        # Compute z-score normalization
        mean_val = df[metric].mean()
        std_val = df[metric].std()
        if std_val == 0:
            df[metric + '_norm'] = 0
        else:
            df[metric + '_norm'] = (df[metric] - mean_val) / std_val
        
        # For MDD, lower values are better, so invert the normalized value.
        if metric == 'MDD':
            df[metric + '_norm'] = -df[metric + '_norm']
    
    # Compute the composite score as a weighted sum of normalized scores.
    composite_scores = np.zeros(len(df))
    for metric, weight in weights.items():
        if metric not in df.columns:
            continue
        composite_scores += df[metric + '_norm'] * weight
    df['Composite Score'] = composite_scores
    
    # Sort portfolios by Composite Score in descending order
    df = df.sort_values(by='Composite Score', ascending=False).reset_index(drop=True)
    
    # Create a Rank column (1 = best)
    df['Rank'] = df.index + 1
    
    # Return only the columns of interest
    return df[['Port_IDs', 'Composite Score', 'Rank']]

In [121]:
ranked_data = composite_ranking(account_metric,weights);
ranked_data.head(20)

               Port_IDs  Composite Score  Rank
0   4020204877254599680         2.495987     1
1   3936410995029308417         2.153554     2
2   3944658614777849089         1.199408     3
3   4012994295026226176         1.026820     4
4   3768170840939476993         0.946006     5
5   4022641794255717633         0.687805     6
6   3999240873283311617         0.651314     7
7   4004713168329653760         0.585772     8
8   4030635536196756737         0.543888     9
9   3956048468100538880         0.528780    10
10  4029506971304830209         0.526241    11
11  4037073643537925121         0.510886    12
12  4030392204221219329         0.509899    13
13  4031408429897920512         0.389241    14
14  3878631538480067329         0.384726    15
15  3956076827719377409         0.369140    16
16  3951723256343550465         0.364621    17
17  3949329502284748801         0.352959    18
18  4030395639953224449         0.346192    19
19  4030708912786799105         0.339638    20